// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG2ST9kJzvcQKXC0bAKx8_TuJUN8-ZMU0',
    appId: '1:1017169645571:web:dff8d448bc8a63041dfe36',
    messagingSenderId: '1017169645571',
    projectId: 'chat-app-ac962',
    authDomain: 'chat-app-ac962.firebaseapp.com',
    storageBucket: 'chat-app-ac962.appspot.com',
    measurementId: 'G-V9YPLJBKH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4W1r7v-8m_aWE4P2bBkQNWz-ywo097wQ',
    appId: '1:1017169645571:android:176bd4753abae5131dfe36',
    messagingSenderId: '1017169645571',
    projectId: 'chat-app-ac962',
    storageBucket: 'chat-app-ac962.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxArA-aqeRTIafTC1Km1ySnHCkY0AOrKA',
    appId: '1:1017169645571:ios:0d33c5bfe598fe0e1dfe36',
    messagingSenderId: '1017169645571',
    projectId: 'chat-app-ac962',
    storageBucket: 'chat-app-ac962.appspot.com',
    iosClientId: '1017169645571-nenh05k5r5vjmrv0t97ec9lguulbhu5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
